{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  labels:
    {{- include "demo-crm.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            {{- if .Values.clusterIssuer.solverIngressClassName }}
            ingressClassName: {{ .Values.clusterIssuer.solverIngressClassName }}
            {{- else }}
            name: {{ default (include "demo-crm.fullname" .) .Values.clusterIssuer.solverIngressName }}
            {{- end }}
{{- end }}
