apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-crm.fullname" . }}
  labels:
    {{- include "demo-crm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "demo-crm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
