apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-crm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.org/redirect-to-https: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: romans-crm.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-crm
            port:
              number: 80
  tls:
  - hosts:
    - romans-crm.ddns.net
    secretName: demo-crm-tls
